/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <LED.h>
#include <LED_aliases.h>
#include <Timer_1.h>
#include <Clock_4.h>
#include <ISR.h>
#include <Channel_1.h>
#include <Channel_1_aliases.h>
#include <Timer_2.h>
#include <Clock_5.h>
#include <ISR_1.h>
#include <Channel_2.h>
#include <Channel_2_aliases.h>
#include <UART_2.h>
#include <UART_2_SPI_UART.h>
#include <UART_2_PINS.h>
#include <UART_2_SPI_UART_PVT.h>
#include <UART_2_PVT.h>
#include <UART_2_BOOT.h>
#include <UART_1.h>
#include <UART_2_SCBCLK.h>
#include <UART_2_tx.h>
#include <UART_2_tx_aliases.h>
#include <UART_2_SCB_IRQ.h>
#include <UART_1_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

