/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Clock_counter.h>
#include <Clock_pwm.h>
#include <isr_1.h>
#include <elbow.h>
#include <elbow_aliases.h>
#include <baseAzimuth.h>
#include <baseAzimuth_aliases.h>
#include <Timer_1.h>
#include <MISO_1.h>
#include <MISO_1_aliases.h>
#include <WIZ_RDY.h>
#include <WIZ_RDY_aliases.h>
#include <WIZ_INT.h>
#include <WIZ_INT_aliases.h>
#include <WIZ_RST.h>
#include <WIZ_RST_aliases.h>
#include <WIZ_SS.h>
#include <WIZ_SS_aliases.h>
#include <BA_PWM.h>
#include <ELBW_PWM.h>
#include <SHLDR_PWM.h>
#include <ADC.h>
#include <pot_elbow.h>
#include <pot_elbow_aliases.h>
#include <pot_shoulder.h>
#include <pot_shoulder_aliases.h>
#include <shoulder.h>
#include <shoulder_aliases.h>
#include <Wrist_UART.h>
#include <Wrist_UART_SPI_UART.h>
#include <Wrist_UART_PINS.h>
#include <Wrist_UART_SPI_UART_PVT.h>
#include <Wrist_UART_PVT.h>
#include <Wrist_UART_BOOT.h>
#include <stop_elb_dn.h>
#include <stop_elb_dn_aliases.h>
#include <MOSI_1.h>
#include <MOSI_1_aliases.h>
#include <SCLK_1.h>
#include <SCLK_1_aliases.h>
#include <SPIM_1.h>
#include <SPIM_1_PVT.h>
#include <stop_elb_up.h>
#include <stop_elb_up_aliases.h>
#include <stop_shdr_dn.h>
#include <stop_shdr_dn_aliases.h>
#include <stop_shdr_up.h>
#include <stop_shdr_up_aliases.h>
#include <LED.h>
#include <LED_aliases.h>
#include <EFFECTOR_PWM.h>
#include <effector_A.h>
#include <effector_A_aliases.h>
#include <Arduino_UART.h>
#include <Arduino_UART_SPI_UART.h>
#include <Arduino_UART_PINS.h>
#include <Arduino_UART_SPI_UART_PVT.h>
#include <Arduino_UART_PVT.h>
#include <Arduino_UART_BOOT.h>
#include <Bootloadable_1.h>
#include <ADC_IRQ.h>
#include <ADC_intClock.h>
#include <Wrist_UART_SCBCLK.h>
#include <Wrist_UART_tx.h>
#include <Wrist_UART_tx_aliases.h>
#include <Wrist_UART_rx.h>
#include <Wrist_UART_rx_aliases.h>
#include <SPIM_1_IntClock.h>
#include <Arduino_UART_SCBCLK.h>
#include <Arduino_UART_tx.h>
#include <Arduino_UART_tx_aliases.h>
#include <Arduino_UART_SCB_IRQ.h>
#include <Arduino_UART_rx.h>
#include <Arduino_UART_rx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

